lines = [
    "They did not do the needful.",
    "børk børk børk!",
    "lapopm",
    "User could not open cryptic email.",
    "Sometimes you need to \"walk the walk\".",
    "¸¸♬·¯·♩¸¸♪·¯·♫¸¸ do the needfull ¸¸♬·¯·♩¸¸♪·¯·♫¸¸",
    "PUMA",
    "¯\_(ツ)_/¯",
    "Mercury must be in retrograde.",
    "Oh wauw!",
    "Oh wauw, oh wauw, oh wauw!",
    "Error initializing smartkroket",
    "Bom dia! 💣",
    "That's to confuse the Russians.",
    "Problem exists between keyboard and chair.",
    "Problem exists between smartcard and chair.",
    "I give you back 3 minutes!",
    "Ik wil niet zeggen dat het prutsers zijn, maar ze zijn wel aan het prutsen.",
    "E.Off",
    "Push the Button",
    "PKI is dry. Please water the PKI.",
    "certificate requests go brrrrrrr",
    "Are you positive?",
    "¸¸♬·¯·♩¸¸♪·¯·♫¸¸ Push the Botton ¸¸♬·¯·♩¸¸♪·¯·♫¸¸",
    "I survived another meeting that should have been an email.",
    "That's just wonderful.",
    "queueueueue",
    "When shit hits the fan, not everyone get's an evenly spread.",
    "Urgent!!!!!",
    "URGENT!!!!!",
    "User did not reply. Closing ticket."
]
