lines = [
    "They did not do the needful.",
    "børk børk børk!",
    "lapopm",
    "User could not open cryptic email.",
    "Sometimes you need to \"walk the walk\".",
    "¸¸♬·¯·♩¸¸♪·¯·♫¸¸ do the needfull ¸¸♬·¯·♩¸¸♪·¯·♫¸¸",
    "PUMA",
    "¯\_(ツ)_/¯",
    "Mercury must be in retrograde.",
    "Oh wauw!",
    "Oh wauw, oh wauw, oh wauw!",
    "Error initializing smartkroket",
    "Bom dia! 💣",
    "That's to confuse the Russians.",
    "Problem exists between keyboard and chair.",
    "Problem exists between smartcard and chair.",
    "I give you back 3 minutes!",
    "Ik wil niet zeggen dat het prutsers zijn, maar ze zijn wel aan het prutsen.",
    "E.Off",
    "Push the Button",
    "PKI is dry. Please water the PKI.",
    "certificate requests go brrrrrrr",
    "Are you positive?",
    "¸¸♬·¯·♩¸¸♪·¯·♫¸¸ Push the Button ¸¸♬·¯·♩¸¸♪·¯·♫¸¸",
    "I survived another meeting that should have been an email.",
    "That's just wonderful.",
    "queueueueue",
    "When shit hits the fan, not everyone get's an evenly spread.",
    "Urgent!!!!!",
    "URGENT!!!!!",
    "User did not reply. Closing ticket.",
    "Let someone empty the bitbucket please!",
    "Yes yes but actually no.",
    "If you're caught fixing it you will be blamed for breaking it.",
    "Segregation of WHAT?",
    "Ah well whatever.",
    "Congratulations! You did not pass the test.",
    "BLUE SCREEN OF D̴̸̪̝͇͈͔̗͓̤̻̞̙ͮ͒̅̏ͤ̅ͭ̓͊ͧ͒͡͡ͅȨ̣͉̥̺̱̬͇̥͎̟͓̱̺̜̯̳͇̄͌͗͋̍͆ͦͬ́ͩͣ̏͗̃̈͗ͨ̄͘͢ͅĀ̧̪͇̯̹͎̹͖̮̺̮̮̪̯̒ͧ̂̕ͅT̈́͒ͬ̔͟͏̭̠̻̖̫̠̹̰̲Ḥ̷̷̡̧̻̟̥̗̋ͫ͋",
    "I � Unicode",
    "Task failed successfully!",
    "A lack of planning on your side does not constitute an emergency on mine.",
    "Technology will find ways to break in new, exciting ways!",
    "Fur de Hurde!!!!",
    "To prevent complaints about The Service, we will no longer be providing The Service.",
    "Redundancy makes you fail twice.",
    "Sometimes, the best part about my job is that my chair spins!",
    "WAZAAA",
    "There's no place like 127.0.0.1",
    "There's no place like ::1",
    "There's no place like ~/",
    "Failing to plan is planning to fail!",
    "I expected nothing and you still managed to disappoint me.",
    "Customer servicedesk tried to reinstall and now it worksn't.",
    "Keep on trying, you can do it.",
    "Hou toch je rollback",
    "If it ain't broken don't fix it.",
    "Vroom vroom! Screeeech! Brrrrrmmmmm!",
    "You can't fix stupid.",
    "You can't fix stupid. Well, actually you can but it's a bloody mess and highly illegal.",
    "Ring ring ring ring ring ring ring / Banana phone! 🍌",
    "Samir, you are breaking the car!",
    "It's a phone with a peel!",
    "I got a bit heavy handed with the md device.",
    "Nom de Dieu de putain de bordel de merde de saloperie de connard d'enculé de ta mère!"
]
